<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2O475OQ" failures="1" tests="4" name="FireFoxTest" time="193.928" errors="0" timestamp="2022-08-06T01:54:32 IST">
  <testcase classname="com.saucedemo.TestClasses.VerifyLoginTestClass" name="verifyLoginFunctionality" time="0.026"/>
  <testcase classname="com.saucedemo.TestClasses.VerifyHomePOMPage" name="verifyHomePageFunctionality" time="5.144"/>
  <testcase classname="com.saucedemo.TestClasses.VerifyLogoutFunctionality" name="verifyLogoutFunctionality" time="5.837"/>
  <testcase classname="com.saucedemo.TestClasses.VerifyMultiProductClass" name="verifyMultiProducts" time="15.398">
    <failure type="java.lang.AssertionError" message="Test Case Passed expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: Test Case Passed expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at com.saucedemo.TestClasses.VerifyMultiProductClass.verifyMultiProducts(VerifyMultiProductClass.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifyMultiProducts -->
</testsuite> <!-- FireFoxTest -->
